### ISSUE TITLE
eth_getCode() returning  " unable to fetch code"

### ISSUE THREAD

**Issue by SantaHub** [0xPolygon/polygon-edge#1023]
# getCode returning unable to fetch code error. 
## Description
When using getCode RPC call on an address, i receive "Unable to fetch error : 32600". If the account is new or a random one i get a 200 response with result "0x" which is the expected response.

## Your environment
- Linux
- v0.6.1
- develop
- EC2 host on AWS
- Not containzered

## Steps to reproduce
- Do an RPC eth_getCode  with data 
 ```
 {
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0x14dc79962da2c08b23698b3d3cc7ca32193d9955",
        "latest"
    ],
    "id": 1
}
```
- Where the issue is, if you know. : Must be on getCode code logic
- Which commands triggered the issue, if any. : eth_getCode()
- Provide us with the content of your genesis file. 
```
{
    "name": "polygon-edge",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000edea9473adbc525751a99dbc05a2a644aad5a261f992d194b2efbd91d281a2efcde6de29091d1a134579787780c0",
        "gasLimit": "0x500000",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0xB8aA26439cB203eEb13b81582E846F6442d28d17": {
                "balance": "0x33b2e3c9fd0803ce8000000"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 100,
        "engine": {
            "ibft": {
                "epochSize": 100000,
                "type": "PoA",
                "validator_type": "ecdsa"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAm4QC9ZejDWdb9NTTYrgo53e48xRAfoAJYPvEkUzLPz7Cu",
        "/ip4/127.0.0.1/tcp/20001/p2p/16Uiu2HAmH7gTpvmLdz4ZXwxTo71m6h4JW5tefKCHAP2T7ewzwKfA"
    ]
}
```

- Validator start Command : 
`polygon-edge server --data-dir ./test-chain-1 --chain genesis.json --grpc-address :10000 --libp2p :10001 --jsonrpc :10002 --seal --log-level DEBUG
`

- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.

- Is the chain producing blocks and serving customers atm? Yes but not customer facing

## Expected behavior
- Tell us what should happen. Expected Response 
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x"
}
```
- Tell us what happened instead.
Error 

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32600,
        "message": "unable to fetch code"
    }
}

```

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

```

2022-12-08T20:42:43.076Z [DEBUG] polygon.server.dispatcher: request: method=eth_getBalance id=7
2022-12-08T20:42:43.076Z [DEBUG] polygon.server.jsonrpc: handle: response="{\"jsonrpc\":\"2.0\",\"id\":9,\"result\":\"0x\"}"
2022-12-08T20:42:43.076Z [DEBUG] polygon.server.jsonrpc: handle: response="{\"jsonrpc\":\"2.0\",\"id\":7,\"result\":\"0x0\"}"
2022-12-08T20:42:43.088Z [DEBUG] polygon.server.jsonrpc: handle: request="{\"id\":12,\"jsonrpc\":\"2.0\",\"method\":\"eth_getCode\",\"params\":[\"0xb8aa26439cb203eeb13b81582e846f6442d28d17\",\"0x27173\"]}"
2022-12-08T20:42:43.088Z [DEBUG] polygon.server.dispatcher: request: method=eth_getCode id=12
2022-12-08T20:42:43.088Z [DEBUG] polygon.server.jsonrpc: handle: request="{\"id\":11,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xb8aa26439cb203eeb13b81582e846f6442d28d17\",\"0x27173\"]}"
2022-12-08T20:42:43.089Z [ERROR] polygon.server.dispatcher: failed to dispatch: method=eth_getCode err="unable to fetch code"
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.jsonrpc: handle: response="{\"jsonrpc\":\"2.0\",\"id\":12,\"error\":{\"code\":-32600,\"message\":\"unable to fetch code\"}}"
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.dispatcher: request: method=eth_getTransactionCount id=11
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.jsonrpc: handle: request="{\"id\":10,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBalance\",\"params\":[\"0xb8aa26439cb203eeb13b81582e846f6442d28d17\",\"0x27173\"]}"
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.dispatcher: request: method=eth_getBalance id=10
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.jsonrpc: handle: response="{\"jsonrpc\":\"2.0\",\"id\":10,\"result\":\"0x33b2e05a7bcd4a3e1e80000\"}"
2022-12-08T20:42:43.089Z [DEBUG] polygon.server.jsonrpc: handle: response="{\"jsonrpc\":\"2.0\",\"id\":11,\"result\":\"0x10\"}"
2022-12-08T20:42:43.101Z [DEBUG] polygon.server.jsonrpc: handle: request="{\"id\":14,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionCount\",\"params\":[\"0xb8aa26439cb203eeb13b81582e846f6442d28d17\",\"0x27173\"]}"

```
## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it
I am not sure why its happening. Might be something corrupting the address ?

**Comment by laviniat1996** [comment]
Hi @SantaHub , thanks for reporting this. 
This error was fixed in [this PR](https://github.com/0xPolygon/polygon-edge/pull/976) and  the fix will be added to the next Edge version.

**Comment by SantaHub** [comment]
Hi @laviniat1996 I am tried building the latest develop branch and this issue still persists. Please note that i am using ecdsa validation instead of ibft.

**Comment by laviniat1996** [comment]
@SantaHub did you build the binary for the latest changes? I was not able to reproduce this on the latest develop branch, using ecdsa. How did you make the switch? Please provide more details, that way is easier to help.

**Comment by SantaHub** [comment]
@laviniat1996 The ecdsa switch ? I made that with my genesis file. I have attached the file above on the initial thread.

 yes i rebuild the polygon-edge binary with the latest develop using the following commad
`go build -o polygon-edge main.go
`

**Comment by SantaHub** [comment]
If you need to verify, these are the steps i follow to get my polygon network running : https://github.com/SantaHub/Foundry_NFT#deploy-local-polygon-network

**Comment by SantaHub** [comment]
@laviniat1996 Hi, i recompiled and the issue seems to be fixed. We might be able to close this, i will confirm in 30 minutes.

**Comment by SantaHub** [comment]
the eth_getCode() error seems to have been fixed ! but i am getting a very ambiguous error during my deployment now ... 

![image](https://user-images.githubusercontent.com/12994795/207039532-54ef0703-25e5-4bcd-b010-62721e3f11b7.png)
![image](https://user-images.githubusercontent.com/12994795/207039595-5f7ae500-2c44-4099-be00-f04abc9c78ef.png)

```


Script ran successfully.

## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:


Failed with `EvmError: RejectCallerWithCode`:

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

  [0] 0x0000000000000000000000000000000000000000::fallback() 
    └─ ← ()

Error: 

Transaction failed when running the on-chain simulation. Check the trace above for more information.

Context:
- Simulated execution failed.
make: *** [deployAll] Error 1
```

**Comment by laviniat1996** [comment]
@SantaHub did you get that error after deploying  that forge script?

**Comment by SantaHub** [comment]
@laviniat1996 Its during deployment. I dont have the contracts created on the chain, any suggestions on finding more info on this error?

**Comment by laviniat1996** [comment]
@SantaHub can you provide the exact steps to follow in order to reproduce that error?

**Comment by SantaHub** [comment]
@laviniat1996 Hi, i was masked by too many forms of the same issue, i believe this above issue has the same root cause as the other issue i posted #1010 . I am closing this issue and providing a better issue documentation on #1010
